project:
  type: website
  output-dir: _site
  resources:
    - "/_redirects"
    - "/netlify.toml"
    - "/.well-known/atproto-did"

highlight-style: a11y

website:
  title: "Bobby"
  site-url: https://bobby50792.com
  repo-url: https://github.com/bobby50792/website
  page-navigation: true
  navbar:
    background: light
    logo: bobby.svg
    logo-alt: "Bobby logo."
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Notes"
        href: docs/notes/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
    right:
      - icon: github
        href: https://github.com/bobby50792/website
        aria-label: GitHub repository

  sidebar:
    - id: notes
      collapse-level: 1
      contents:
        - section: "Notes"
          href: docs/notes/index.qmd
format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

filters:
  - filters/tools-tabset.lua
  - filters/color-box.lua
  - at: post-quarto
    path: filters/include-dark.lua

version: '1.9'
prerelease-subdomain: ''

freeze: true

profile:
  group:
    - [prerelease, rc]
