project:
  type: website
  output-dir: _site
  resources:
    - "/_redirects"
    - "/netlify.toml"
    - "/.well-known/atproto-did"

highlight-style: a11y

website:
  title: "Bobby"
  site-url: https://bobby50792.com
  repo-url: https://github.com/bobby50792/website
  page-navigation: true
  navbar:
    background: light
    logo: bobby.svg
    logo-alt: "Bobby logo."
    title: false
    collapse-below: lg
    left:
      - text: "Notes"
        href: docs/notes/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
    right:
      - icon: github
        href: https://github.com/bobby50792/website
        aria-label: GitHub repository

  sidebar:
    - id: notes
      collapse-level: 1
      contents:
        - section: "Notes"
          href: docs/notes/index.qmd
          contents:
            - section: "Calculus"
              href: docs/notes/Calculus/index.qmd
              contents: 
                - text: "Real Numbers and Limits of Sequences"
                  href: docs/notes/Calculus/1.qmd
                - text: "Continuity of Functions"
                  href: docs/notes/Calculus/2.qmd
                - text: "Derivatives and Differentials of Functions"
                  href: docs/notes/Calculus/3.qmd
                - text: "Indefinite Integrals"
                  href: docs/notes/Calculus/4.qmd
                - text: "Definite Integrals"
                  href: docs/notes/Calculus/5.qmd
                - text: "Ordinary Differential Equations"
                  href: docs/notes/Calculus/6.qmd
                - text: "Limits and Continuity of Multivariate Functions"
                  href: docs/notes/Calculus/7.qmd
                - text: "Differential of Multivariable Functions"
                  href: docs/notes/Calculus/8.qmd
                - text: "Implicit Function and Inverse Mapping Theorem"
                  href: docs/notes/Calculus/9.qmd
                - text: "Integrals with Parameters and Improper Integrals"
                  href: docs/notes/Calculus/10.qmd
                - text: "Multiple Integrals"
                  href: docs/notes/Calculus/11.qmd
                - text: "Integration of Functions on Curves and Surfaces"
                  href: docs/notes/Calculus/12.qmd
            - section: "Math for CS and AI"
              href: docs/notes/Math4CS&AI/index.qmd
              contents: 
                - text: "Discrete Probability"
                  href: docs/notes/Math4CS&AI/1.qmd
                - text: "Sampling and Concentration"
                  href: docs/notes/Math4CS&AI/2.qmd
                - text: "Generating Functions"
                  href: docs/notes/Math4CS&AI/3.qmd
                - text: "Continuous Probability"
                  href: docs/notes/Math4CS&AI/4.qmd
            - section: "General Physics"
              href: docs/notes/Physics/index.qmd
              contents: 
                - text: "Classical Mechanics"
                  href: docs/notes/Physics/1.qmd
format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

filters:
  - filters/tools-tabset.lua
  - filters/color-box.lua
  - at: post-quarto
    path: filters/include-dark.lua

version: '1.9'
prerelease-subdomain: ''

freeze: false

profile:
  group:
    - [prerelease, rc]
